baseurl = "https://bdw.to/"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Ben Woodward"
title = "Ben Woodward"
pygmentsuseclasses = true
pygmentsstyle = "manni"
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
Author = "Ben Woodward"
CacheBuster = true
DateForm = "Jan 2, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
Description = "The personal website of Ben Woodward"
Email = "ben@bdw.to" # TODO:
FaviconFile = "img/leaf.ico"
GATracker = "XYZ" # TODO:
GitHub = "//github.com/bndw"
Lang = "en"
LinkedIn = "//linkedin.com/in/benwoodward"
ExtraCssFiles = [] # relative to public directory
