version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-buster
    steps:
      - checkout
      - setup_remote_docker
      - run: make build
      - run: make publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
